// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const http: typeof import('axios')['default']
  const IconCarbonLight: typeof import('~icons/carbon/light.jsx')['default']
  const IconCarbonMoon: typeof import('~icons/carbon/moon.jsx')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout.jsx')['default']
  const IconPhUserDuotone: typeof import('~icons/ph/user-duotone.jsx')['default']
}
export {}
